services:
  - name: auth-backend
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn authbackend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: auth-db
          property: connectionString

databases:
  - name: auth-db
    region: oregon
    plan: free
    postgresMajorVersion: 14
